#!/usr/bin/env bash

function main {
  local phome="$1"; shift
  local pth_cache="$1"; shift
  local pth_env="$1"; shift

  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  install -v -d "$phome/script"

  local pth_script
  for pth_script in $(set +f; ls -d "$shome/script/"*); do
    local nm_script="${pth_script##*/}"
    if [[ -f "$phome/script/$nm_script" ]]; then
      echo "INFO: skipping $nm_script, a script already exists"
    else
      install -v -m 0755 "$pth_script" "$phome/script/$nm_script"
    fi
  done
}

source sub "$0" "$@"
