#!/usr/bin/env bash

## script/bootstrap is used solely for fulfilling dependencies of the project.
## This can mean RubyGems, npm packages, Git submodules, etc. The goal is to make
## sure all required dependencies are installed.

function main {
  local shome="${_scripts_to_rule_them_all_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  
  true
}

main "$@"
