#!/usr/bin/env bash

## script/cibuild is used for your continuous integration server. This script is
## typically only called from your CI server. You should set up any specific
## things for you environment here before your tests are run. Your test are run
## simply by calling script/test.

function setup {
  echo 999 > state.tmp
  mv state.tmp state
}

function main {
  setup
  script/test
}

source script/profile
main "$@"
