#!/usr/bin/env bash

## script/cibuild is used for your continuous integration server. This script is
## typically only called from your CI server. You should set up any specific
## things for you environment here before your tests are run. Your test are run
## simply by calling script/test.

function setup {
  true
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  setup
  "$shome/script/test"
}

main "$@"
