#!/usr/bin/env bash

## script/profile is used to initialize an environment in a bash shell or
## script.

function _scripts_to_rule_them_all_profile {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  PATH="$shome/exec:$PATH"
}

_scripts_to_rule_them_all_profile
