#!/usr/bin/env bash

## script/server is used to start the application. For a web application, this
## might start up any extra processes that the application requires to run in
## addition to itself. script/update should be called ahead of any application
## booting to ensure that the application is up to date and can run appropriately.

function server {
  true
}

function main {
  local shome="${_scripts_to_rule_them_all_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  "$shome/script/update"
  server
}

main "$@"
