#!/usr/bin/env bash

## script/setup is used to set up a project in an initial state. This is typically
## run after an initial clone, or, to reset the project back to its initial state.
## This is also useful for ensuring that your bootstrapping actually works well.

function setup {
  true
}

function main {
  local shome="${_scripts_to_rule_them_all_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  "$shome/script/bootstrap"
  setup
}

main "$@"
