#!/usr/bin/env bash

## script/test is used to run the test suite of the application. A good pattern to
## support is having an optional argument that is a file path. This allows you to
## support running single tests. script/test should be called from script/cibuild,
## so it should handle setting up the application appropriately based on the
## environment. For example, if called in a development environment, it should
## probably call script/update to always ensure that the application is up to
## date. If called from script/cibuild, it should probably reset the application
## to a clean state.

function testing {
  true
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  "$shome/script/setup" || "$shome/script/update"
  testing
}

main "$@"
