#!/usr/bin/env bash

## script/update is used to update the project after a fresh pull. If you have not
## worked on the project for a while, running script/update after a pull will
## ensure that everything inside the project is up to date and ready to work.
## Typically, script/bootstrap is run inside this script. This is also a good
## opportunity to run database migrations or any other things required to get the
## state of the app into shape for the current version that is checked out.

function migrate {
  echo "$(( $(cat state) + 1 ))" > state.tmp
  mv state.tmp state
}

function main {
  script/bootstrap
  migrate
}

main "$@"
